version: '3.8'

services:
  bot:
    build: .
    environment:
      - VAUTO_USERNAME=${VAUTO_USERNAME}
      - VAUTO_PASSWORD=${VAUTO_PASSWORD}
      - NODE_ENV=production
      - MODE=web
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      # Mount data directory for persistent storage
      - ./data:/app/data
      # Add shared memory for browser
      - /dev/shm:/dev/shm
    # Add shared memory size for browser
    shm_size: '2gb'
    restart: unless-stopped
    # Add security options for browser
    security_opt:
      - seccomp:unconfined
    # Web interface mode - provides GUI for managing JSON file
    command: ["node", "src/app.js"]
