version: '3.8'

services:
  bot:
    build: .
    container_name: vehicle-bot
    environment:
      - NODE_ENV=production
      - MODE=scrape  # or 'web' for web interface
      - PORT=3000
      # Add your environment variables here
      # - CARMAX_EMAIL=your-email@example.com
      # - CARMAX_PASSWORD=your-password
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/app/data
      - ./user_data:/usr/src/app/user_data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Optional: Add a reverse proxy like nginx if needed
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - bot
  #   restart: unless-stopped
