[build]
cmd = "npm ci"

[start]
cmd = "./start-nixpacks.sh"

[env]
NODE_ENV = "production"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"  # Let Puppeteer use system Chromium
DISPLAY = ":99"

[phases.setup]
# Install Chromium + Node.js + Xvfb
nixpkgs = ["nodejs_20", "xvfb-run", "chromium"]

# Optional: Only needed if Coolify blends apt (some Coolify setups do)
aptPkgs = [
  "ca-certificates",
  "fonts-liberation",
  "libasound2",
  "libatk-bridge2.0-0",
  "libatk1.0-0",
  "libdrm2",
  "libgtk-3-0",
  "libnspr4",
  "libnss3",
  "libxss1",
  "libxtst6",
  "xdg-utils",
  "libgbm1",
  "libxcomposite1",
  "libxcursor1",
  "libxdamage1",
  "libxfixes3",
  "libxi6",
  "libxrandr2",
  "libxrender1",
  "xvfb",
  "dbus"
]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "npm ci"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "echo '✅ Build complete - Puppeteer will use system Chromium'"
]